%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Released as part of the codebase to replicate results reported in
% "Method to determine whether sleep phenotypes are driven by endogenous circadian
% rhythms or environmental light by combining longitudinal data and personalised mathematical models"
% Skeldon et al, PLoS Comput Biol, provisionally accepted Dec 2023.
%
% Author: A.C. Skeldon, a.skeldon@surrey.ac.uk, University of Surrey, 2023.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Code to plot out Arnold tongue data generated by run_Arnold_tongue.m
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  addpath('../data_generated/')
%
  data = readtable('Arnold_tongue_20230923.dat')
%
  idx_start = 1;
  p1     = data.Var1(idx_start:end); % Light
  p2     = data.Var2(idx_start:end); % Tau
  SD     = data.Var3(idx_start:end); % Sleep duration
  MSF    = data.Var5(idx_start:end); % Mid-sleep
  MSF_sd = data.Var6(idx_start:end); % Standard deviation of mid-sleep (used to evaluate if solution
                                     % has converged to a periodic solution.
%
  MSF(MSF>16)      = MSF(MSF>16) - 24;  
  MSF(MSF_sd>0.02) = -10;
  Wake             = MSF + 0.5*SD;
%
  p1vals  = unique(p1);
  np1     = length(p1vals);
  p2vals = unique(p2);
  np2    = length(p2vals);
%
  p2(find(p1 == p1vals(1)))
%
% Contour plot
%
  p1_tot  = repmat(p1vals',np2,1);
  p2_tot  = repmat(p2vals,1,np1);
  SD_tot  = reshape(SD,np2,np1);
  MSF_tot = reshape(MSF,np2,np1);
  Wake_tot = reshape(Wake,np2,np1);
%
  figure(1)
  subplot(1,3,1)
  [C,h]=contourf(p2_tot,log10(p1_tot),SD_tot,'ShowText','on');
  hold on
  title('Sleep duration')
  xlabel('\tau')
  ylabel('Light')
  set(gca,'TickDir','out')
%
  subplot(1,3,2)
  [C,h]=contourf(p2_tot,log10(p1_tot),MSF_tot,[-12:24],'ShowText','on');
  hold on
  title('MSF')
  xlabel('\tau')
  ylabel('Day light')
  plot([24.15 24.15],[1 4],'--','Color',[1 1 1],'LineWidth',2)
  plot([23.5 24.7],log10([700 700]),'--','Color',[1 1 1],'LineWidth',2)
%
  subplot(1,3,3)
  [C,h]=contourf(p2_tot,log10(p1_tot),Wake_tot,[-12:24],'ShowText','on');
  hold on
  title('Wake')
  xlabel('\tau')
  ylabel('Day light')
  plot([24.15 24.15],[1 4],'--','Color',[1 1 1],'LineWidth',2)
  plot([23.5 24.7],log10([700 700]),'--','Color',[1 1 1],'LineWidth',2)
  set(gca,'TickDir','out')
%
